spring.application.name=TrabajoParcial
server.port=8081

# Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/db_trabajoParcial
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Manejo de Errores
server.error.include-stacktrace=never

# Logs
logging.level.root=INFO
logging.level.com.upc.proveedores=DEBUG

# --- CONFIGURACION JWT ---
# Clave secreta para firmar los tokens (Debe ser larga por seguridad)
jwt.secret=M1_CL4V3_S3CR3T4_M0Y_L4RG4_Y_S3GUR4_P4R4_3L_PR0Y3CT0
# Tiempo de expiración en milisegundos (Ejemplo: 86400000 ms = 24 horas)
jwt.expiration=86400000

# Cloudinary (US11)
cloudinary.cloud_name=dxk84ewvl
cloudinary.api_key=418478639481879
cloudinary.api_secret=lXFAPn7KPPc7BDgLoKJOvY7RfHA
